//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Level_Exporter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Level_Exporter.Resources.WindowStrings", typeof(WindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this text field is blank, a save file dialog will open for every level to export..
        /// </summary>
        public static string BrowseTextFieldToolTip {
            get {
                return ResourceManager.GetString("BrowseTextFieldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dwg.
        /// </summary>
        public static string CadTypeDwg {
            get {
                return ResourceManager.GetString("CadTypeDwg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dxf.
        /// </summary>
        public static string CadTypeDxf {
            get {
                return ResourceManager.GetString("CadTypeDxf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emcam.
        /// </summary>
        public static string CadTypeEmcam {
            get {
                return ResourceManager.GetString("CadTypeEmcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iges.
        /// </summary>
        public static string CadTypeIges {
            get {
                return ResourceManager.GetString("CadTypeIges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igs.
        /// </summary>
        public static string CadTypeIgs {
            get {
                return ResourceManager.GetString("CadTypeIgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcam.
        /// </summary>
        public static string CadTypeMcam {
            get {
                return ResourceManager.GetString("CadTypeMcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CAD Format.
        /// </summary>
        public static string CadTypePrompt {
            get {
                return ResourceManager.GetString("CadTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sat.
        /// </summary>
        public static string CadTypeSat {
            get {
                return ResourceManager.GetString("CadTypeSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step.
        /// </summary>
        public static string CadTypeStep {
            get {
                return ResourceManager.GetString("CadTypeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stl.
        /// </summary>
        public static string CadTypeStl {
            get {
                return ResourceManager.GetString("CadTypeStl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stp.
        /// </summary>
        public static string CadTypeStp {
            get {
                return ResourceManager.GetString("CadTypeStp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x_b.
        /// </summary>
        public static string CadTypeXb {
            get {
                return ResourceManager.GetString("CadTypeXb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmt_txt.
        /// </summary>
        public static string CadTypeXmttxt {
            get {
                return ResourceManager.GetString("CadTypeXmttxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x_t.
        /// </summary>
        public static string CadTypeXt {
            get {
                return ResourceManager.GetString("CadTypeXt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Directory (leave blank to open file dialog on export).
        /// </summary>
        public static string DestinationPrompt {
            get {
                return ResourceManager.GetString("DestinationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CAD.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Mastercam Levels.
        /// </summary>
        public static string GetLevelsButton {
            get {
                return ResourceManager.GetString("GetLevelsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Mastercam Levels.
        /// </summary>
        public static string SyncLevelsButton {
            get {
                return ResourceManager.GetString("SyncLevelsButton", resourceCulture);
            }
        }
    }
}
